// <auto-generated />
using ColorWheelAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ColorWheelAPI.Migrations
{
    [DbContext(typeof(ColorWheelDbContext))]
    [Migration("20190204224631_SeedColor")]
    partial class SeedColor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ColorWheelAPI.Models.Color", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColorName");

                    b.Property<string>("HexCode");

                    b.HasKey("ID");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ColorName = "Yellow",
                            HexCode = "#FEFE33"
                        },
                        new
                        {
                            ID = 2,
                            ColorName = "Yellow-Green",
                            HexCode = "#B2D732"
                        },
                        new
                        {
                            ID = 3,
                            ColorName = "Green",
                            HexCode = "#66B032"
                        },
                        new
                        {
                            ID = 4,
                            ColorName = "Blue-Green",
                            HexCode = "#347C98"
                        },
                        new
                        {
                            ID = 5,
                            ColorName = "Blue",
                            HexCode = "#0247FE"
                        },
                        new
                        {
                            ID = 6,
                            ColorName = "Blue-Violet",
                            HexCode = "#4424D6"
                        },
                        new
                        {
                            ID = 7,
                            ColorName = "Violet",
                            HexCode = "#8601AF"
                        },
                        new
                        {
                            ID = 8,
                            ColorName = "Red-Violet",
                            HexCode = "#C21460"
                        },
                        new
                        {
                            ID = 9,
                            ColorName = "Red",
                            HexCode = "#FE2712"
                        },
                        new
                        {
                            ID = 10,
                            ColorName = "Red-Orange",
                            HexCode = "#FC600A"
                        },
                        new
                        {
                            ID = 11,
                            ColorName = "Orange",
                            HexCode = "#FB9902"
                        },
                        new
                        {
                            ID = 12,
                            ColorName = "Yellow-Orange",
                            HexCode = "#FCCC1A"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
